# Generated by Django 4.2.1 on 2023-05-24 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configwall",
            name="conf",
            field=models.CharField(max_length=5000),
        ),
    ]
